### ISSUE TITLE
Great progress!

### ISSUE THREAD

**Issue by pmwoodward3** [nap/plexcleaner#2]
I've been following you commits and I'm really impressed by how fast it's all (seemingly) coming together! Really great work.

Really looking forward to using it! :)

**Comment by nap** [comment]
Thanks!

Yeah, I really want to get this done ASAP.
I had a drawback with the first release because I did not notice that the Plex database had strict permissions assign to it. The app kept on complaining that the Plex database was encrypted. So now the app might require to run with elevated privileges (aka. root) or I'll prompt the user to run as the "plex" user that is created when you install PMS.
